const fs = require('fs')

const HEARTBEAT_FILE = '/var/run/imageserver_heartbeat'
const HEARTBEAT_INTERVAL = 10000

/** Touch the heartbeat file once (async).
 */
function touch () {
  fs.open(HEARTBEAT_FILE, 'w', (err, fd) => {
    if (err) throw err
    fs.close(fd, err => { if (err) throw err })
  })
  console.log('TOUCH')
}

let interval

/** Setup a heartbeat file using export events generated by the given app.
 *
 * @param {electron app} app
 */
function setupHeartbeat (app) {
  app.on('before-export', (info) => {
    clearInterval(interval)
    touch()
    console.log('Starting export; stopping heartbeat')
  })

  app.on('after-export', (info) => {
    touch()
    interval = setInterval(touch, HEARTBEAT_INTERVAL)
    console.log('Export done; heartbeat started')
  })

  interval = setInterval(touch, HEARTBEAT_INTERVAL)
  console.log('Initial load; heartbeat started')
}

module.exports = setupHeartbeat
